package com.flexfit.comm.svc.fedex_core.enums;

/**
 * U.S. Region Service List
 * <br/>
 * <a href="https://developer.fedex.com/api/ko-kr/guides/api-reference.html#servicetypes">Reference</a>
 */
public enum ServiceType {
    FEDEX_INTERNATIONAL_PRIORITY_EXPRESS,
    INTERNATIONAL_FIRST,
    FEDEX_INTERNATIONAL_PRIORITY,
    INTERNATIONAL_ECONOMY,
    FEDEX_GROUND,
    FIRST_OVERNIGHT,
    FEDEX_FIRST_FREIGHT,
    FEDEX_1_DAY_FREIGHT,
    FEDEX_2_DAY_FREIGHT,
    FEDEX_3_DAY_FREIGHT,
    INTERNATIONAL_PRIORITY_FREIGHT,
    INTERNATIONAL_ECONOMY_FREIGHT,
    FEDEX_INTERNATIONAL_DEFERRED_FREIGHT,
    INTERNATIONAL_PRIORITY_DISTRIBUTION,
    INTERNATIONAL_DISTRIBUTION_FREIGHT,
    INTL_GROUND_DISTRIBUTION,
    GROUND_HOME_DELIVERY,
    SMART_POST,
    PRIORITY_OVERNIGHT,
    STANDARD_OVERNIGHT,
    FEDEX_2_DAY,
    FEDEX_2_DAY_AM,
    FEDEX_EXPRESS_SAVER,
    SAME_DAY,
    SAME_DAY_CITY
}

